# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'email.mime.base',
        'email.mime.application',
        'email.encoders',
        'email.generator',
        'email.header',
        'email.message',
        'email.parser',
        'email.policy',
        'email.utils',
        'email.charset',
        'email.contentmanager',
        'email.errors',
        'ssl',
        'socket',
        'select',
        'selectors',
        '_ssl',
        'encodings',
        'encodings.utf_8',
        'encodings.ascii',
        'encodings.latin_1',
        'encodings.idna',
        'urllib3',
        'urllib3.util',
        'urllib3.util.retry',
        'urllib3.util.timeout',
        'urllib3.util.url',
        'urllib3.util.ssl_',
        'urllib3.util.connection',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.certs',
        'requests.cookies',
        'requests.exceptions',
        'requests.models',
        'requests.sessions',
        'requests.utils',
        'httpx',
        'httpcore',
        'httpcore._async',
        'httpcore._sync',
        'anyio',
        'anyio._backends._asyncio',
        'certifi',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.sip',
        'pandas',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'test',
        'xmlrpc',
        'pydoc',
        'doctest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PolymarketTool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    target_arch='arm64',
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='PolymarketTool',
)

app = BUNDLE(
    coll,
    name='PolymarketTool.app',
    icon=None,
    bundle_identifier='com.keenan.polymarkettool',
    info_plist={
        'CFBundleShortVersionString': '1.0.0',
        'CFBundleVersion':            '1.0.0',
        'NSHighResolutionCapable':    True,
        'LSMinimumSystemVersion':     '12.0',
        'NSRequiresAquaSystemAppearance': False,
    },
)
